FROM docker.io/crystallang/crystal:latest AS builder
WORKDIR /src
COPY shards /shards
COPY shard.yml .
RUN shards install
COPY src ./src
RUN shards build --error-trace --release --progress --static

FROM docker.io/library/ubuntu:latest
# alpine podman version is too new, and I'm too lazy to learn how to install an older one
RUN apt update && apt install -y podman
COPY --from=builder /src/src/public /src/src/public
COPY --from=builder /src/bin/endash /bin/endash
ENTRYPOINT ["/bin/endash"]
