FROM docker.io/crystallang/crystal:latest-alpine AS builder
WORKDIR /src
COPY --from=lemur . /shards/lemur
COPY --from=geode . /shards/geode
COPY --from=status_page . /shards/status_page
COPY shard.yml .
RUN shards install
COPY src ./src
RUN shards build --error-trace --release --progress --static

FROM docker.io/library/alpine:latest
RUN apk add podman
COPY --from=builder /src/src/public /src/src/public
COPY --from=builder /src/bin/endash /bin/endash
ENTRYPOINT ["/bin/endash"]
