FROM docker.io/crystallang/crystal:latest-alpine AS builder
# alpine podman version is too new, and I'm too lazy to learn how to install an older one
RUN apk add podman
WORKDIR /src
COPY --from=lemur . /shards/lemur
COPY --from=podman-cr . /shards/podman-cr
COPY shard.yml .
RUN shards update
VOLUME /root/.cache/crystal
ENTRYPOINT ["shards", "run", "--error-trace", "--"]
