FROM docker.io/crystallang/crystal:latest-alpine AS builder
WORKDIR /src
COPY shard.* .
RUN shards install
COPY . .
RUN shards build --error-trace --release --progress --static

FROM docker.io/library/alpine:latest
RUN apk add podman
COPY --from=builder /src/src/public /src/src/public
COPY --from=builder /src/bin/endash /bin/endash
ENTRYPOINT ["/bin/endash"]
